REMOTE_URL:
  "http://anovanatho.com/get.php?username=ravi.sidhu@gmail.com&password=XP85AofAjc&type=m3u_plus&output=mpegts"
FILTER_FILE:
  "config/anovafaves.txt"
INPUT_FILE:
  "raw.m3u"
OUTPUT_FILE:
  "output/out.m3u"
# A neat progress bar for large M3Us. Might not work on Linux. If so, change to False
USE_PROGRESS_BAR:
  True